### ISSUE TITLE
Matlab example

### ISSUE THREAD

**Issue by kul-create** [greenwom/2006_Groeneveld_CriticalHeatFlux_LUT#1]
Hej,

Thank you for your very useful script: do you maybe have some example of a command that works and that can be paste in Matlab's Command Window to receive results, e.g. Groeneveld_LUT(1000,700000,0.5... etc? Somehow I cannot get the command working.

Sincerely,
Lukasz

**Comment by greenwoodms06** [comment]
Unfortunately I do not have Matlab. I imagine it should work but I am unable to provide any assistance.
